In [1]:
import doctest
import numpy as np

In [61]:
def func(A, A_inv, x):
    l = A_inv.dot(x)
    if l[0] == 0:
        raise Exception('A_hat is singular.')
    else:
        l_hat = l.copy()
        l_hat[k] = -1
        q = (-1/l[k]) * l_hat
        Q = np.identity(m)
        Q[:,k] = q
        A_hat_inv = Q.dot(A_inv)
        return A_hat_inv

In [16]:
def inv(C):
    """
    >>> C = np.array([[0, 0, 2], [0, 1, 0], [2, -4, 0]])
    >>> C.dot()
    array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])
    """
    m, _ = C.shape
    A, A_inv = np.identity(m), np.identity(m)
    used_set, r = set(), np.zeros(m)
    for i in range(m):
        j = choose_column(i, C, A_inv, used_set)
        r[i] = j
        used_set.add(j)
        A_hat = A.copy(); A_hat[:,i] = C[:,j]
        l = A_inv.dot(C[:,j])
        l_hat = l.copy(); l_hat[i] = -1
        q = (-1/l[i]) * l_hat
        Q = A_inv.copy(); Q[:,i] = q
        A_hat_inv = Q.dot(A_inv)
        A, A_inv = A_hat, A_hat_inv
    return A_inv[:,r.astype(int)]
        
        
def choose_column(i, C, A_inv, used):
    m, _ = C.shape
    for j in (j for j in range(m) if j not in used):
        l = A_inv.dot(C[:, j])
        if l[i] != 0:
            return j
    raise Exception('The C is singular')
    
C = np.array([[0, 0, 2], [0, 1, 0], [2, -4, 0]])
C.dot(inv(C))

array([[  1.   ,  12.   ,   0.   ],
       [  0.   ,   1.   ,   0.   ],
       [  0.   ,  -4.   ,   0.125]])

In [10]:
C = np.array([[0,0,2], [0,1,0], [2, -4, 0]])
C

array([[ 0,  0,  2],
       [ 0,  1,  0],
       [ 2, -4,  0]])

In [12]:
C[:,[1,0,2]]

array([[ 0,  0,  2],
       [ 1,  0,  0],
       [-4,  2,  0]])

In [106]:
inv(C)

[ 2.  1.  0.]


array([[-1. , -1. ,  0.2],
       [-5. ,  4. , -0.2],
       [ 7. , -2. , -0.2]])

In [2]:
from numpy import linalg

In [5]:
C.dot(linalg.inv(C))

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])