In [1]:
import numpy as np

In [2]:
def dual_simplex(A, b, c, y, j_b):
    _, m = A.shape
    
    # нахождение коплана
    delta = y.dot(A) - c
    while True:
        A_b = A[:, j_b]
        B = np.linalg.inv(A_b)
        
        # нахождение базисных компонентов псевдоплана
        ksi_b = B.dot(b)
        if np.all(ksi_b >= 0):
            opt_plan = np.zeros((m, ))
            opt_plan[j_b] = ksi_b
            return opt_plan

        k = np.argwhere(ksi_b < 0).min()
        j_k = np.argwhere(j_b).take(k)
        mu = B[k,:].dot(A)
        j_n = j_b == False
        sigma = np.array([-d/n if n < 0 else np.infty for d, n in zip(delta[j_n], mu[j_n])])
        s_0 = sigma.argmin()
        sigma_0 = sigma[s_0]
        
        if sigma_0 == np.infty:
            raise Exception('Incompatible constraints')
            
        j_0 = np.argwhere(j_n).take(s_0)
        
        # построение нового двойственного плана
        y = y + sigma_0*B[k]
        
        # построение нового коплана
        delta = y.dot(A) - c # y + sigma_0 * nu
        j_b = (np.abs(delta) < 1e-8)

## Variant 0.1

In [3]:
A = np.array([
    [-2, -1, 1, -7, 0, 0, 0, 2],
    [4, 2, 1, 0, 1, 5, -1, -5],
    [1, 1, 0, -1, 0, 3, -1, 1]
])

c = np.array([2, 2, 1, -10, 1, 4, -2, -3])
b = np.array([-2, 4, 3], dtype=np.float)
y_0 = np.array([1, 1, 1])
j_b = np.array([False, True, False, False, True, False, True, False])

dual_simplex(A, b, c, y_0, j_b).round(2)

array([ 0.  ,  2.67,  0.  ,  0.  ,  0.33,  0.  ,  0.  ,  0.33])

## Variant 0.2 ! b[3] = -b[3] (minus)

In [4]:
A = np.array([
    [-2, -1, 1, -7, 0, 0, 0, 2],
    [4, 2, 1, 0, 1, 5, -1, -5],
    [1, 1, 0, 1, 0, 3, 1, 1]
])

c = np.array([2, 2, 1, -10, 1, 4, 0, -3])
b = np.array([-2, 4, -3], dtype=np.float)
y_0 = np.array([1, 1, 1])
j_b = np.array([False, True, False, False, True, False, True, False])

try:
    dual_simplex(A, b, c, y_0, j_b).round(2)
except:
    print('Incompatible constraints')

Incompatible constraints


## Variant 1

In [5]:
A = np.array([
    [-2, -1, 1, -7, 0, 0, 0, 2],
    [4, 2, 1, 0, 1, 5, -1, -5],
    [1, 1, 0, -1, 0, 3, -1, 1]
])

c = np.array([5, 2, 3, -16, 1, 3, -3, -12], dtype=np.float)
b = np.array([-2, -4, -2], dtype=np.float)
y_0 = np.array([1, 2, -1])
j_b = np.array([True, True, True, False, False, False, False, False])

dual_simplex(A, b, c, y_0, j_b).round(2)

array([ 0. ,  0. ,  0. ,  0.4,  0. ,  0. ,  2. ,  0.4])

## Varian 2

In [6]:
A = np.array([
    [-2, -1, 1, -7, 1, 0, 0, 2],
    [-4, 2, 1, 0, 5, 1, -1, 5],
    [1, 1, 0, -1, 0, 3, -1, 1]
])

c = np.array([-12, 2, 2, -6, 10, -1, -9, 8])
b = np.array([-2, 4, -2], dtype=np.float)
y_0 = np.array([1, 2, -1])
j_b = np.array([False, True, False, True, False, True, False, False])

dual_simplex(A, b, c, y_0, j_b).round(2)

array([ 0.,  0.,  5.,  1.,  0.,  0.,  1.,  0.])

## Variant 3

In [7]:
A = np.array([
    [-2, -1, 1, -7, 1, 0, 0, 2],
    [-4, 2, 1, 0, 5, 1, -1, 5],
    [1, 1, 0, 1, 4, 3, 1, 1]
])

c = np.array([12, -2, -6, 20, -18, -5, -7, -20])
b = np.array([-2, 8, -2], dtype=np.float)
y_0 = np.array([-3, -2, -1])
j_b = np.array([False, True, False, True, False, True, False, False])

try:
    dual_simplex(A, b, c, y_0, j_b).round(2)
except:
    print('Incompatible constraints')

Incompatible constraints


## Variant 4

In [8]:
A = np.array([
    [-2, -1, 10, -7, 1, 0, 0, 2],
    [-4, 2, 3, 0, 5, 1, -1, 0],
    [1, 1, 0, 1, -4, 3, -1, 1]
])

c = np.array([10, -2, -38, 16, -9, -9, -5, -7])
b = np.array([-2, -5, 2], dtype=np.float)
y_0 = np.array([-3, -2, -1])
j_b = np.array([False, True, False, False, True, False, False, True])

dual_simplex(A, b, c, y_0, j_b).round(2)

array([ 1.35,  0.2 ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.45])

## Variant 5

In [9]:
A = np.array([
    [3, -1, 10, -7, 1, 0, 0, 2],
    [7, -2, 14, 8, 0, 12, -11, 0],
    [1, 1, 0, 1, -4, 3, -1, 1]
])

c = np.array([36, -12, 66, 76, -5, 77, -76, -7])
b = np.array([2, 5, -2], dtype=np.float)
y_0 = np.array([-3, 7, -1])
j_b = np.array([False, False, False, True, False, False, True, True])

dual_simplex(A, b, c, y_0, j_b).round(2)

array([ 0.  ,  0.  ,  0.26,  0.17,  0.54,  0.  ,  0.  ,  0.  ])

In [10]:
A = np.array([
    [-2, -1, -4, 1, 0],
    [-2, -2, -2, 0, 1]
])

c = np.array([-4, -3, -7, 0, 0])
b = np.array([-1, -1.5], dtype=np.float)
y_0 = np.array([0, 0])
j_b = np.array([False, False, False, True, True])

dual_simplex(A, b, c, y_0, j_b).round(2)

array([ 0.25,  0.5 ,  0.  ,  0.  ,  0.  ])